'use strict';
const fs = require('node:fs'); const path = require('node:path'); const crypto = require('node:crypto'); const { createDatabase, migrate } = require('../db.js');
const file = path.resolve(process.env.LEGACY_JSON_FILE || path.join(__dirname, '..', 'data', 'oneofus-payments.json'));
function stableUuid(value) { const hex = crypto.createHash('sha256').update(String(value)).digest('hex'); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-8${hex.slice(17, 20)}-${hex.slice(20, 32)}`; }
async function main() {
  if (!fs.existsSync(file)) throw new Error(`Legacy JSON file not found: ${file}`);
  const state = JSON.parse(fs.readFileSync(file, 'utf8')); const pool = createDatabase(); await migrate(pool); const client = await pool.connect(); let imported = 0; const malformed = [];
  try { await client.query('BEGIN');
    for (const participant of state.participants || []) await client.query(`INSERT INTO participants (id, name, payout_wallet, created_at, updated_at) VALUES ($1,$2,$3,$4,$4) ON CONFLICT (id) DO NOTHING`, [participant.id, participant.displayName || 'Anonymous', participant.payoutWallet, participant.createdAt || new Date()]);
    for (const order of state.orders || []) {
      if (!order.id || !order.participantId || !order.expectedPaymentAmount) { malformed.push(order.id || 'unknown order'); continue; }
      const participant = (state.participants || []).find((item) => item.id === order.participantId);
      if (!participant) { malformed.push(`${order.id}: missing participant`); continue; }
      await client.query(`INSERT INTO participants (id, name, payout_wallet, created_at, updated_at) VALUES ($1,$2,$3,$4,$4) ON CONFLICT (id) DO NOTHING`, [participant.id, participant.displayName || order.participantName || 'Anonymous', participant.payoutWallet, participant.createdAt || order.createdAt]);
      const createdAt = new Date(order.createdAt); const opensAt = new Date(Date.UTC(createdAt.getUTCFullYear(), createdAt.getUTCMonth(), createdAt.getUTCDate())); const closesAt = new Date(opensAt.getTime() + 24 * 60 * 60 * 1000);
      const round = await client.query(`INSERT INTO rounds (id, status, opens_at, closes_at, draw_at, carry_in_amount, gross_pool_amount, organizer_fee_amount, winner_pool_amount, paid_ticket_count, free_ticket_count, created_at, updated_at) VALUES ($1,'locked',$2,$3,$3,0,0,0,0,0,0,now(),now()) ON CONFLICT (opens_at) DO UPDATE SET updated_at = rounds.updated_at RETURNING id`, [crypto.randomUUID(), opensAt, closesAt]);
      const roundId = round.rows[0].id;
      const inserted = await client.query(`INSERT INTO orders (id, participant_id, round_id, ticket_quantity, sending_source, base_ticket_amount, ticket_value_amount, identification_amount, payment_code, expected_payment_amount, payment_status, created_at, expires_at, cooldown_until, paid_at, transaction_hash, transaction_log_index, block_number, received_amount, ticket_range_start, ticket_range_end) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) ON CONFLICT (id) DO NOTHING RETURNING id`, [order.id, order.participantId, roundId, order.ticketQuantity, order.sendingSource, order.baseTicketAmount, order.ticketValueAmount, order.identificationAmount, order.paymentCode, order.expectedPaymentAmount, order.paymentStatus, order.createdAt, order.expiresAt, order.cooldownUntil, order.paidAt, order.transactionHash, order.transactionLogIndex, order.blockNumber, order.receivedAmount, order.ticketRangeStart, order.ticketRangeEnd]);
      if (inserted.rowCount) imported += 1;
      await client.query(`INSERT INTO payment_code_reservations (id, order_id, full_expected_amount, payment_code, status, reserved_at, expires_at, cooldown_until, active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (order_id) DO NOTHING`, [crypto.randomUUID(), order.id, order.expectedPaymentAmount, order.paymentCode, order.paymentStatus, order.createdAt, order.expiresAt, order.cooldownUntil, Date.parse(order.cooldownUntil) > Date.now()]);
      if (order.ticketRangeStart !== null && order.ticketRangeStart !== undefined) await client.query(`INSERT INTO ticket_ranges (id, order_id, participant_id, round_id, start_ticket, end_ticket, created_at) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (order_id) DO NOTHING`, [crypto.randomUUID(), order.id, order.participantId, roundId, order.ticketRangeStart, order.ticketRangeEnd, order.paidAt || order.createdAt]);
    }
    for (const event of state.events || []) if (event.transactionHash && event.transactionLogIndex !== undefined) await client.query(`INSERT INTO payments (id, order_id, transaction_hash, log_index, block_number, token_address, to_address, received_amount, detected_at, payment_status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (transaction_hash) DO NOTHING`, [crypto.randomUUID(), event.orderId, event.transactionHash, event.transactionLogIndex, event.blockNumber, '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', process.env.ONE_OF_US_RECEIVING_ADDRESS?.toLowerCase() || '', event.amount, event.detectedAt, event.status]);
    await client.query(`INSERT INTO ticket_ledger_entries (id, round_id, order_id, participant_id, payment_id, ticket_type, cause, ticket_count, start_ticket, end_ticket, created_at)
      SELECT md5('legacy-ledger-' || t.id::text)::uuid, t.round_id, t.order_id, t.participant_id, p.id, 'paid', 'legacy_import', (t.end_ticket - t.start_ticket + 1)::integer, t.start_ticket, t.end_ticket, t.created_at
      FROM ticket_ranges t JOIN payments p ON p.order_id = t.order_id AND p.payment_status = 'confirmed'
      ON CONFLICT (order_id) DO NOTHING`);
    for (const draw of state.draws || []) await client.query(`INSERT INTO draw_history (id, draw_date, status, total_paid_tickets, pool_amount, prize_amount, winner_name, winner_payout_wallet, winning_ticket_number, payout_transaction_hash, is_demo, created_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) ON CONFLICT (id) DO NOTHING`, [stableUuid(draw.id), draw.drawDate, draw.drawStatus, draw.totalPaidTickets, draw.poolAmount, draw.prizeAmount, draw.winnerName, draw.winnerPayoutWallet, draw.winningTicketNumber, draw.payoutTransactionHash, draw.isDemo, draw.createdAt]);
    if (state.chainCursor !== null && state.chainCursor !== undefined) await client.query(`INSERT INTO scanner_state (scanner_name, last_processed_block) VALUES ('arbitrum-usdt',$1) ON CONFLICT (scanner_name) DO UPDATE SET last_processed_block = EXCLUDED.last_processed_block, updated_at = now()`, [state.chainCursor]);
    if (state.nextTicket) await client.query(`UPDATE app_counters SET next_value = GREATEST(next_value, $1) WHERE name = 'ticket'`, [state.nextTicket]);
    await client.query('COMMIT'); console.log(`Imported ${imported} orders from ${file}.`); if (malformed.length) console.warn(`Skipped malformed records: ${malformed.join(', ')}`);
  } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); await pool.end(); }
}
main().catch((error) => { console.error(error.message); process.exitCode = 1; });
